// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDB7dZkV4hfZwL5wKX2D2V9fzptpKxVw',
    appId: '1:502199231877:web:3df55a681d523b6ee510ec',
    messagingSenderId: '502199231877',
    projectId: 'rigiflow-d5c42',
    authDomain: 'rigiflow-d5c42.firebaseapp.com',
    storageBucket: 'rigiflow-d5c42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOu5Rk6QZZwxwgrzjwaVaI1OB6a5_VHz8',
    appId: '1:502199231877:android:3cd32605db035553e510ec',
    messagingSenderId: '502199231877',
    projectId: 'rigiflow-d5c42',
    storageBucket: 'rigiflow-d5c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00voE1Up_IIuQJXU-wRhhM3B5lFcdfNw',
    appId: '1:502199231877:ios:aed987a153bf5631e510ec',
    messagingSenderId: '502199231877',
    projectId: 'rigiflow-d5c42',
    storageBucket: 'rigiflow-d5c42.firebasestorage.app',
    iosBundleId: 'com.rurigi.rigiflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00voE1Up_IIuQJXU-wRhhM3B5lFcdfNw',
    appId: '1:502199231877:ios:aed987a153bf5631e510ec',
    messagingSenderId: '502199231877',
    projectId: 'rigiflow-d5c42',
    storageBucket: 'rigiflow-d5c42.firebasestorage.app',
    iosBundleId: 'com.rurigi.rigiflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFDB7dZkV4hfZwL5wKX2D2V9fzptpKxVw',
    appId: '1:502199231877:web:e56cf1522c123025e510ec',
    messagingSenderId: '502199231877',
    projectId: 'rigiflow-d5c42',
    authDomain: 'rigiflow-d5c42.firebaseapp.com',
    storageBucket: 'rigiflow-d5c42.firebasestorage.app',
  );
}
